name: Upload mutual-tls-interface

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/charms/mutual_tls_interface/v0/**"

jobs:
  charmhub-upload:
    runs-on: ubuntu-22.04
    name: Charmhub upload lib
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: canonical/charming-actions/upload-charm@2.2.5
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "edge"
          upload-image: "false"

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          charmcraft publish-lib charms.mutual_tls_interface.v0.mutual_tls
